name: tramdoc
description: "Ung dung Tram Doc - Tro ly doc sach va on tap thong minh."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- UI & DESIGN SYSTEM ---
  # Icon set giống hệt bản thiết kế Figma (Quan trọng)
  lucide_icons: ^0.257.0
  # Font chữ Google (Dùng font Inter hoặc Merriweather cho sách)
  google_fonts: ^6.1.0
  # Hiệu ứng chuyển động mượt mà (Fade in, Slide in...)
  flutter_animate: ^4.5.0
  # Hỗ trợ hiển thị file ảnh Vector (SVG)
  flutter_svg: ^2.0.9
  # Hiệu ứng kính mờ (Glassmorphism) cho Header/BottomBar
  glassmorphism: ^3.0.0

  # --- STATE MANAGEMENT & NAVIGATION ---
  # Quản lý trạng thái (Theo báo cáo giữa kỳ của bạn)
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  # Điều hướng màn hình chuyên nghiệp
  go_router: ^12.0.0

  # --- FEATURES (TÍNH NĂNG) ---
  # Chọn ảnh từ thư viện hoặc chụp ảnh
  image_picker: ^1.2.1
  # Xử lý ngày tháng (VD: "2 giờ trước")
  intl: ^0.18.1

  # --- FIREBASE & AI (Chuẩn bị cho Tuần 6-7) ---
  # firebase_core: ^2.24.2
  # firebase_auth: ^4.16.0
  # cloud_firestore: ^4.14.0
  # google_mlkit_text_recognition: ^0.11.0 # Để quét chữ OCR

  # Icon mặc định của iOS
  cupertino_icons: ^1.0.2
  provider: ^6.1.5+1
  http: ^1.6.0
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  firebase_auth: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # --- KHAI BÁO TÀI NGUYÊN (QUAN TRỌNG) ---
  # Bạn nhớ tạo đúng 2 thư mục này trong project nhé!
  assets:
    - assets/images/
#    - assets/icons/